app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    pass_code = db.Column(db.String(255))
    pitches = db.relationship('Pitch',backref = 'user', lazy = 'dynamic')
    comments = db.relationship('Comment',backref = 'user',lazy = "dynamic")
  

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_code = generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.pass_code,password)    

    def __repr__(self):
        return f'User {self.username}'

class Pitch(db.Model):
    __tablename__='pitches'

    id = db.Column(db.Integer,primary_key = True)
    title = db.Column(db.String)
    pitch = db.Column(db.String)
    time = db.Column(db.DateTime,default=datetime.utcnow)
    user_id = db.Column(db.Integer,db.ForeignKey("users.id")) 
    pitch_comments = db.relationship('Comment',backref = 'pitch',lazy = "dynamic")

    def save_pitch(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_pitch(cls,id):
        
        pitch = Pitch.query.filter_by(id=id).first()
        
        return pitch      

    def __repr__(self):
        return f'User {self.title}'

class Comment(db.Model):
    __tablename__='comments'

    id = db.Column(db.Integer,primary_key = True)
    pitch_comment = db.Column(db.String)
    pitch_id = db.Column(db.Integer,db.ForeignKey("pitches.id")) 
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))        

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls,id):
        comments = Comment.query.filter_by(pitch_id=id).all()
        return comments

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField
from wtforms.validators import Required

class PitchForm(FlaskForm):
    title = StringField('Pitch title',validators=[Required()])
    pitch = TextAreaField('Pitch')
    submit = SubmitField('Submit')

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.', validators=[Required()])
    submit = SubmitField('Submit')

class CommentForm(FlaskForm):
    comment = TextAreaField('Comment') 
    submit = SubmitField('Submit')
.

app/__init__.py
from flask import Flask
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail

bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
photos = UploadSet('photos',IMAGES)
mail = Mail()

def create_app(config_name):

    app = Flask(__name__)

    app.config.from_object(config_options[config_name])

    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    configure_uploads(app,photos)
    mail.init_app(app)
     
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors
.

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from ..models import User,Pitch,Comment
from .forms import UpdateProfile,PitchForm,CommentForm
from .. import db,photos
from flask_login import login_required,current_user
from datetime import datetime

@main.route('/')
def index():
    pitches = Pitch.query.order_by(Pitch.time.desc()).all()

    return render_template('index.html', pitches = pitches)
    
@main.route('/add',methods = ['GET','POST'])
@login_required
def add_pitch():
    form = PitchForm()

    if form.validate_on_submit():
        pitch = Pitch(title = form.title.data, pitch = form.pitch.data,user=current_user)
        
        db.session.add(pitch)
        db.session.commit()

        return redirect(url_for('main.index'))
         
    return render_template('add.html',pitch_form=form)

@main.route('/pitch/<int:id>')
def pitch(id):

    pitch = Pitch.query.filter_by(id=id).first()
    comments = Comment.get_comments(pitch.id)

    return render_template('pitch.html',comments = comments, pitch = pitch)

@main.route('/pitch/comment/new/<int:id>', methods =  ['GET','POST'])
@login_required
def new_comment(id):
    form = CommentForm() 
    pitch = Pitch.query.filter_by(id=id).first()
    if form.validate_on_submit():
        comment = form.comment.data
        new_comment = Comment(pitch_comment=comment,pitch_id = pitch.id,user=current_user) 
        
        new_comment.save_comment()
        
        return redirect(url_for('.pitch',id = pitch.id))

    return render_template('new_comment.html',comment_form=form, pitch=pitch)  

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)    

@main.route('/user/<uname>/update',methods = ['GET', 'POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form=form)

@main.route('/user/<uname>/update/pic',methods=['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname)).
                       

app/templates/add.html
{% extends 'base.html' %}  
{% import 'bootstrap/wtf.html' as wtf%}

{% block content %}
<div class="container-fluid bg-image">
  <div class="row styler">
    
  </div>
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      {{wtf.quick_form(pitch_form)}}
    </div>
    <div class="col-md-4"></div>
  </div>
</div>

{% endblock %}

app/templates/base.html
{% extends 'bootstrap/base.html'%}


{% block styles%}
    {{ super() }}
    <link href="https://fonts.googleapis.com/css2?family=Grenze+Gotisch:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Ranchers&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
{% endblock %}

{% block content%}

{% endblock%}

app/templates/index.html
{% extends 'base.html' %} 
{% import 'macros.html' as macro%}


{% block content %}
<div class="container-fluid">
  <div class="row poster">
    <nav>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="/"> 1 Minute rush </a></li>
          <li><a href="/">Home</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          {% if current_user.is_authenticated %}
          <li>
            <a href="{{url_for('main.add_pitch')}}"
              >Add Pitch</a
            >
            </li>
            <li>
            <a href="{{url_for('main.profile',uname=current_user.username)}}"
              >Profile</a
            >
          </li>
          <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
          {% else %}
          <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
          {%endif%}
        </ul>
      </div>
    </nav>
  </div>
 
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      {{ macro.displayPitches(pitches)}}
    </div>
    <div class="col-md-2"></div>
  </div>
</div>

{% endblock %}

app/templates/macros.html
{% macro displayPitches(pitch_list) %}

    {% for pitch in pitch_list %}
    <div class="container">
      <h2>{{ pitch.title }}</h2> 
      <p>{{ pitch.pitch }}</p>
      <p><em>{{ pitch.user.username }}</em></p>
      <p>({{ pitch.time.strftime('%B %d,%y /%H:%m') }})</p>
      <a href="{{url_for('main.pitch', id = pitch.id)}}" class=" btn btn-primary">Comments</a> 
    </div>
    <hr>
    {% endfor %}
{% endmacro %}

{% macro displayComments(comment_list) %}
  {% for comment in comment_list %}
   <div class="row">
   <p>{{ comment.pitch_comment }}</p>
   <p>
    <strong>Author:</strong>
    {{ comment.user.username }}
    </p>
    <hr>
   </div>
  {% endfor %}

{% endmacro %}

app/templates/new_comment.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
{% endblock %}

{% block content %}
    <div class="container-fluid bg-image">
       <div class="row">
          <div class="col-md-3"></div>
          <div class="col-md-6">
           {{ wtf.quick_form(comment_form) }}
          </div>
          <div class="col-md-3"></div>
       </div>
    </div>

{% endblock %}

app/templates/notfound.html
{% extends 'base.html'%}


{% block content %}
<div class="container-fluid">
    <nav>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="/"> 1 Minute rush </a></li>
            <li><a href="/">Home</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if current_user.is_authenticated %}
            <li>
              <a href="{{url_for('main.add_pitch')}}"
                >Add Pitch</a
              >
              </li>
              <li>
              <a href="{{url_for('main.profile',uname=current_user.username)}}"
                >Profile</a
              >
            </li>
            <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
            {% else %}
            <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
            {%endif%}
          </ul>
        </div>
      </nav>
</div>
    <div class="jumbotron">
     <h1>Page Not Found!!!</h1>
     <p>Check the Url you keyed in.</p>
    </div>
{% endblock %}

app/templates/pitch.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}

{% block content %}
<div class="container-fluid">
 <div class="row poster2">
  <nav>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a class="navbar-brand" href="/"> 1 Minute rush </a></li>
        <li><a href="/">Home</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if current_user.is_authenticated %}
        <li>
          <a href="{{url_for('main.add_pitch')}}"
            >Add Pitch</a
          >
          </li>
          <li>
          <a href="{{url_for('main.profile',uname=current_user.username)}}"
            >Profile</a
          >
        </li>
        <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
        {% else %}
        <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
        {%endif%}
      </ul>
    </div>
  </nav>
 </div>

 <div class="row">
    <div class="col-md-6">
     <h2>{{ pitch.title }}</h2> 
     <p>{{ pitch.pitch }}</p>
     <p><em>{{ pitch.user.username }}</em></p>
     <p>({{ pitch.time }})</p>
     <a class="btn btn-primary text-center" href="{{url_for('main.new_comment',id = pitch.id)}}"> Write a new comment</a>
    </div>
    <div class="col-md-6">
     <h1>Comments</h1>
     <hr>
 
     {% if comments %}
        {{ macro.displayComments(comments)}}
 
     {% else%}
         <h3 class="text-center">This pitch has no reviews </h3>
 
         <a class="btn btn-primary text-center" href="{{url_for('main.new_comment',id = pitch.id)}}"> Write a new comment</a>
     {% endif %}
    </div>
  </div>
</div>

</div>

{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container-fluid">
   
  <div class="row poster">
    <nav>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="/"> 1 Minute rush </a></li>
          <li><a href="/">Home</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          {% if current_user.is_authenticated %}
          <li>
            <a href="{{url_for('main.add_pitch')}}"
              >Add Pitch</a
            >
            </li>
            <li>
            <a href="{{url_for('main.profile',uname=current_user.username)}}"
              >Profile</a
            >
          </li>
          <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
          {% else %}
          <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
          {%endif%}
        </ul>
      </div>
    </nav>
  </div>
  <div class="container">  
    <div class="row">
      <div class="col-md-4">
       <h3> {{user.username| capitalize}} </h3>

      {% if user.bio %}
        <p> {{user.bio}} </p>
      {% else %}
        <p> {{user.username| capitalize}} has no bio </p>
      {% endif %}  
   
   
        <a href="{{url_for('main.update_profile',uname=user.username)}}" class=" btn btn-primary">Update Profile</a>
   
      </div>

      <div class="col-md-4">

      {% if user.profile_pic_path %}
        <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class=" img-thumbnail">
      {% else %}
        <p>No profile picture</p>
      {% endif %}

      </div>
      <div class="col-md-4">
      {% if user == current_user %}
       <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

       <input type="file"  name="photo" class="form-control" required>
       <input type="submit">
       </form>
      {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container-fluid bg-image">
<div class="row styler"></div>
<div class="row">
<div class="col-md-2"> </div>
<div class="col-md-8">

{{wtf.quick_form(form)}}

</div>
<div class="col-md-2"></div>
</div>
</div>

{% endblock %}